on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v2

    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y eatmydata
        sudo eatmydata apt-get install -y --no-install-suggests --no-install-recommends build-essential devscripts equivs
        mk-build-deps -irs sudo -t "apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends -y"
    - name: Build
      run: |
        make -j$(nproc)
    - name: Clean
      run: |
        make clean
    - name: Build (package)
      run: |
        dch -l+`git rev-parse --short HEAD` "actions package build"
        debuild -b

  test-package:
    strategy:
      matrix:
        os: ["buster", "bullseye"]
        cpu: ["i386", "amd64", "armhf", "aarch64"]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build Debian package
      uses: dawidd6/action-debian-package@v1
      with:
        source_directory: .
        artifacts_directory: output/${{matrix.os}}/${{matrix.cpu}}
        os_distribution: ${{ matrix.os }}
        cpu_architecture: ${{ matrix.cpu }}
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: output
